[project]
name = "liffe-rate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "pandas>=2.0.3",
    "selenium>=4.25.0",
    "tabulate>=0.9.0",
    "tqdm>=4.66.6",
]
